[workspace]

members = [
    "free_running",
    "no_std",
    "print_os",
    "window",
    "gtk-window",
    "snappy",
]


#only for the free_running crate
#[profile.dev]
#panic = "abort"
#
#[profile.release]
#panic = "abort"